package io.contractguardian.github;

import io.contractguardian.model.Finding;
import io.contractguardian.model.ScanResult;
import io.contractguardian.model.Severity;
import io.contractguardian.model.Verdict;
import io.contractguardian.model.VerdictStatus;

/**
 * Formats a scan {@link Verdict} as a GitHub-flavored Markdown comment.
 *
 * <p>The generated comment includes a hidden marker so that
 * {@link GitHubPrReporter} can find and update an existing comment
 * rather than posting duplicates.
 */
public class GitHubMarkdownFormatter {

    /** Hidden HTML comment used to identify existing contract-guardian PR comments. */
    public static final String MARKER = "<!-- contract-guardian -->";

    /**
     * Formats the verdict as a Markdown string suitable for posting to a GitHub PR.
     *
     * @param verdict the scan verdict to format
     * @return the formatted Markdown string, beginning with the hidden marker
     */
    public String format(final Verdict verdict) {
        final StringBuilder sb = new StringBuilder();
        sb.append(MARKER).append("\n");
        sb.append("## Contract Guardian — Scan Results\n\n");
        sb.append(statusBadge(verdict.status())).append("\n\n");

        if (verdict.results().isEmpty()) {
            sb.append("No contract files changed in this PR.\n");
            return sb.toString();
        }

        sb.append("| File | Status | Findings |\n");
        sb.append("|------|--------|----------|\n");

        for (final ScanResult result : verdict.results()) {
            final String fileStatus = result.hasBreaking() ? ":x: BREAKING"
                    : result.hasWarnings() ? ":warning: WARNING"
                    : ":white_check_mark: PASS";
            final long count = result.findings().stream()
                    .filter(f -> f.severity() != Severity.INFO)
                    .count();
            sb.append(String.format("| `%s` | %s | %d finding(s) |\n",
                    result.file(), fileStatus, count));
        }

        final boolean hasIssues = verdict.results().stream()
                .anyMatch(r -> r.hasBreaking() || r.hasWarnings());

        if (hasIssues) {
            sb.append("\n### Details\n\n");
            for (final ScanResult result : verdict.results()) {
                for (final Finding finding : result.findings()) {
                    if (finding.severity() == Severity.INFO) {
                        continue;
                    }
                    sb.append(findingIcon(finding.severity()))
                            .append(" **[").append(finding.severity()).append("]** ")
                            .append(finding.message()).append("\n");
                    if (finding.fix() != null) {
                        sb.append("  > 💡 ").append(finding.fix()).append("\n");
                    }
                }
            }
        }

        sb.append("\n---\n");
        sb.append(String.format("_Scanned %d file(s) — %d breaking, %d warning(s). "
                        + "Generated by [Contract Guardian](https://github.com/vyndra-io/contract-guardian)._\n",
                verdict.results().size(), verdict.breakingCount(), verdict.warningCount()));

        return sb.toString();
    }

    private String statusBadge(final VerdictStatus status) {
        return switch (status) {
            case FAIL -> "### :x: BUILD BLOCKED — Breaking contract changes detected";
            case WARN -> "### :warning: WARNING — Potential compatibility issues detected";
            case PASS -> "### :white_check_mark: PASS — No breaking contract changes";
        };
    }

    private String findingIcon(final Severity severity) {
        return switch (severity) {
            case BREAKING -> ":x:";
            case WARNING -> ":warning:";
            case INFO -> ":information_source:";
        };
    }
}
